image_field_in_field_detail: 1
field_in_field_list : 9
comment_example_avatar: https://i.pinimg.com/564x/97/bb/06/97bb067e30ff6b89f4fbb7b9141025ca.jpg
format_date: "%H:%M"
admin:
  booking_fields_pagy: 20
  time_format: "%H:%M"
  date_format: "%m-%d-%Y"
calendar:
  time_format: "%H:%M"
  date_format: "%m-%d-%Y"
  start_time: "06:00"
  end_time: "23:30"
  interval: 30
  month_year_format: "%B, %Y"
  change_week: 1
  GMT: "GMT+07"
field:
  minute_step: 30
  price_step: 0.01
image:
  file_type: "image/png,image/gif,image/jpeg"
example_field_image: https://i.pinimg.com/564x/6f/11/db/6f11dbd25aa96cc6f699362839dc9d0b.jpg
time_interval: 30
users:
  avatar_size_50: 50
  pagy_10: 10
